/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-04-26 05:51:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.petsitter;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>PET SITTER</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../main.css\">\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.1/examples/blog/\">\r\n");
      out.write("    <script src=\"header.html\"></script>\r\n");
      out.write("    <script src=\"footer.html\"></script>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("      <!-- Bootstrap core CSS -->\r\n");
      out.write("      <!-- CSS only -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" >\r\n");
      out.write("  <div class=\"p- p-md-5 mb-4 text-white rounded \" style=\"background-color: peachpuff;\">\r\n");
      out.write("          <img class=\"d-block mx-auto mb-4\" src=\"../logo.png\" alt=\"\" width=\"300\" height=\"150\">\r\n");
      out.write("          <h2>펫시터 목록</h2>\r\n");
      out.write("          <p class=\"lead\">위드펫에서 우리 반려동물에게 적합한 펫시터를 찾아보세요!</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("      \r\n");
      out.write("            <!-- Navigation-->\r\n");
      out.write("            <nav class=\"navbar navbar-expand-lg navbar-white\">\r\n");
      out.write("              <div class=\"container px-4 px-lg-5\">\r\n");
      out.write("                  <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\r\n");
      out.write("                  <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("                      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4\">\r\n");
      out.write("                          <li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"#!\">Home</a></li>\r\n");
      out.write("                          <li class=\"nav-item\"><a class=\"nav-link\" href=\"#!\">About</a></li>\r\n");
      out.write("                          <li class=\"nav-item dropdown\">\r\n");
      out.write("                              <a class=\"nav-link dropdown-toggle\" id=\"navbarDropdown\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Shop</a>\r\n");
      out.write("                              <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("                                  <li><a class=\"dropdown-item\" href=\"#!\">All Products</a></li>\r\n");
      out.write("                                  <li><hr class=\"dropdown-divider\" /></li>\r\n");
      out.write("                                  <li><a class=\"dropdown-item\" href=\"#!\">Popular Items</a></li>\r\n");
      out.write("                                  <li><a class=\"dropdown-item\" href=\"#!\">New Arrivals</a></li>\r\n");
      out.write("                              </ul>\r\n");
      out.write("                          </li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                      <form class=\"d-flex\">\r\n");
      out.write("                          <button class=\"btn btn-outline-dark\" type=\"submit\">\r\n");
      out.write("                              <i class=\"bi-cart-fill me-1\"></i>\r\n");
      out.write("                              장바구니 \r\n");
      out.write("                              <span class=\"badge bg-dark text-white ms-1 rounded-pill\">0</span>\r\n");
      out.write("                          </button>\r\n");
      out.write("                      </form>\r\n");
      out.write("                  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Section-->\r\n");
      out.write("<section class = \"py-5\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"col mb-5\">\r\n");
      out.write("      <div class=\"card h-100\">\r\n");
      out.write("          <!-- Sale badge-->\r\n");
      out.write("          <div class=\"badge bg-dark text-white position-absolute\" style=\"top: 0.5rem; right: 0.5rem\">Sale</div>\r\n");
      out.write("          <!-- Product image-->\r\n");
      out.write("          <img class=\"card-img-top\" src=\"https://dummyimage.com/450x300/dee2e6/6c757d.jpg\" alt=\"...\" />\r\n");
      out.write("          <!-- Product details-->\r\n");
      out.write("          <div class=\"card-body p-4\">\r\n");
      out.write("              <div class=\"text-center\">\r\n");
      out.write("                  <!-- Product name-->\r\n");
      out.write("                  <h5 class=\"fw-bolder\"> </h5>\r\n");
      out.write("                  <!-- Product price-->\r\n");
      out.write("                  <span class=\"text-muted text-decoration-line-through\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- Product actions-->\r\n");
      out.write("          <div class=\"card-footer p-4 pt-0 border-top-0 bg-transparent\">\r\n");
      out.write("              <div class=\"text-center\"><a class=\"btn btn-outline-dark mt-auto\" href=\"#\">펫시터 예약</a></div>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<!-- Footer-->\r\n");
      out.write("<footer class=\"py-5 bg-dark\">\r\n");
      out.write("<div class=\"container\"><p class=\"m-0 text-center text-white\"> With Pet &copy; 2022</p></div>\r\n");
      out.write("</footer>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("</main>\r\n");
      out.write("<!-- JavaScript Bundle with Popper -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
