/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-04-26 07:35:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.product;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class review_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>review form</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/main.css\">\r\n");
      out.write("    <link rel=\"canonical\" href=\"https://getbootstrap.com/docs/5.1/examples/blog/\">\r\n");
      out.write("    <script src=\"header.html\"></script>\r\n");
      out.write("    <script src=\"footer.html\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("      function kakaopost() {\r\n");
      out.write("          new daum.Postcode({\r\n");
      out.write("              oncomplete: function(data) {\r\n");
      out.write("                 document.querySelector(\"#zipcode\").value = data.zonecode;\r\n");
      out.write("                 document.querySelector(\"#address\").value =  data.address\r\n");
      out.write("              }\r\n");
      out.write("          }).open();\r\n");
      out.write("      }\r\n");
      out.write("      </script>\r\n");
      out.write("</head>\r\n");
      out.write("    <body>\r\n");
      out.write("      <!-- Bootstrap core CSS -->\r\n");
      out.write("      <!-- CSS only -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" >\r\n");
      out.write("  <div class=\"p- p-md-5 mb-4 text-white rounded \" style=\"background-color: peachpuff;\">\r\n");
      out.write("    <img class=\"d-block mx-auto mb-4\" src=\"../logo.png\" alt=\"\" width=\"300\" height=\"150\">\r\n");
      out.write("    <h2>마이 페이지</h2>\r\n");
      out.write("    <p class=\"lead\">Below is an example form built entirely with Bootstrap’s form controls. Each required form group has a validation state that can be triggered by attempting to submit the form without completing it.</p>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"row g-5\">\r\n");
      out.write("    <div class=\"col-md-5 col-lg-4 order-md-last\">\r\n");
      out.write("      <h4 class=\"d-flex justify-content-between align-items-center mb-3\">\r\n");
      out.write("        <span class=\"text-primary\">마이 페이지</span>\r\n");
      out.write("      </h4>\r\n");
      out.write("      <ul class=\"list-group mb-3\">\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between lh-sm\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h6 class=\"my-0\"><a href=\"product.html\">정보 수정</a></h6>\r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between lh-sm\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h6 class=\"my-0\"><a href=\"#\">주문 및 배송</a></h6>\r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between lh-sm\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h6 class=\"my-0\"><a href=\"review.html\">상품평 작성</a></h6>\r\n");
      out.write("           \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"list-group-item d-flex justify-content-between lh-sm\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <h6 class=\"my-0\"><a href=\"#\">상품 문의</a></h6>\r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-7 col-lg-8\">\r\n");
      out.write("      <h4 class=\"mb-3\">상품평 작성 </h4>\r\n");
      out.write("      <form action=\"reviewadddb.jsp\" method=\"post\" class=\"needs-validation\" novalidate>\r\n");
      out.write("        <div class=\"row g-3\">\r\n");
      out.write("            <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("            <label for=\"newname\" class=\"form-label\">별  점</label>\r\n");
      out.write("            <div class=\"star-rating space-x-4 mx-auto\">\r\n");
      out.write("                <input type=\"radio\" id=\"5-stars\" name=\"score\" value=\"5\" v-model=\"ratings\"/>\r\n");
      out.write("                <label for=\"5-stars\" class=\"star pr-4\">★</label>\r\n");
      out.write("                <input type=\"radio\" id=\"4-stars\" name=\"score\" value=\"4\" v-model=\"ratings\"/>\r\n");
      out.write("                <label for=\"4-stars\" class=\"star\">★</label>\r\n");
      out.write("                <input type=\"radio\" id=\"3-stars\" name=\"score\" value=\"3\" v-model=\"ratings\"/>\r\n");
      out.write("                <label for=\"3-stars\" class=\"star\">★</label>\r\n");
      out.write("                <input type=\"radio\" id=\"2-stars\" name=\"score\" value=\"2\" v-model=\"ratings\"/>\r\n");
      out.write("                <label for=\"2-stars\" class=\"star\">★</label>\r\n");
      out.write("                <input type=\"radio\" id=\"1-star\" name=\"score\" value=\"1\" v-model=\"ratings\" />\r\n");
      out.write("                <label for=\"1-star\" class=\"star\">★</label>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("              <label for=\"newname\" class=\"form-label\">상품평</label>\r\n");
      out.write("            <textarea name=\"content\" class=\"form-control\" id=\"review\" rows=\"10\" cols=\"50\"></textarea>\r\n");
      out.write("            <div class=\"invalid-feedback\"></div>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <hr class=\"my-4\">\r\n");
      out.write("\r\n");
      out.write("        <button type=\"submit\" class=\"w-100 btn btn-primary btn-lg\" type=\"submit\">작성 완료</button>\r\n");
      out.write("\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</main>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"my-5 pt-5 text-muted text-center text-small\">\r\n");
      out.write("  <p class=\"mb-1\">&copy; 2022 WITHPET</p>\r\n");
      out.write("  <ul class=\"list-inline\">\r\n");
      out.write("    <li class=\"list-inline-item\"><a href=\"#\">Privacy</a></li>\r\n");
      out.write("    <li class=\"list-inline-item\"><a href=\"#\">Terms</a></li>\r\n");
      out.write("    <li class=\"list-inline-item\"><a href=\"#\">Support</a></li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</footer>\r\n");
      out.write("       </div>\r\n");
      out.write("       </div>\r\n");
      out.write("</main>\r\n");
      out.write("<!-- JavaScript Bundle with Popper -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
